name: makeway_tracker
description: A car tracking todo app for MakeWay game on Steam
publish_to: 'none'

version: 1.1.2+8
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  file_picker: ^6.1.1
  cupertino_icons: ^1.0.6
  fl_chart: ^0.68.0
  uuid: ^4.5.2
  hotkey_manager: ^0.2.3
  package_info_plus: ^8.1.2
  http: ^1.2.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # If you want to add an app icon, uncomment and add icon files:
  assets:
  - assets/mw-logo4app.png
  - assets/banner.png
